import {
  createId,
  EVENT_CATEGORY_LABELS,
  getStateAtYear,
  latestTemporalState,
  type WikiArticle,
  type WikiCategory,
  type WikiEntityType,
  type WorldProject,
} from "./world";

function findAutoArticle(articles: WikiArticle[], mapId: string, entityId: string, entityType: WikiEntityType): WikiArticle | undefined {
  return articles.find((article) =>
    article.sourceMapId === mapId
    && article.sourceEntityId === entityId
    && article.sourceEntityType === entityType,
  );
}

function categoryIdFor(project: WorldProject, systemKey: WikiCategory): string | null {
  return project.wikiCategories.find((category) => category.systemKey === systemKey)?.id ?? null;
}

function createAutoArticle(
  project: WorldProject,
  mapId: string,
  entityId: string,
  entityType: WikiEntityType,
  title: string,
  summary: string,
  category: WikiArticle["category"],
  tags: string[],
): WikiArticle {
  const now = new Date().toISOString();
  return {
    id: createId("wiki-auto"),
    title,
    category,
    categoryId: categoryIdFor(project, category),
    summary,
    content: "",
    tags,
    linkedMapEntityIds: [entityId],
    sourceMapId: mapId,
    sourceEntityId: entityId,
    sourceEntityType: entityType,
    autoGenerated: true,
    createdDate: now,
    lastModifiedDate: now,
  };
}


function locationWikiCategory(locationType: string): WikiCategory {
  if (["capital", "city", "town"].includes(locationType)) return "city";
  if (locationType === "village") return "village";
  if (["ruin", "dungeon"].includes(locationType)) return "fortress";
  if (locationType === "sacred_site") return "base";
  return "location";
}

function eventWikiCategory(category: string): WikiCategory {
  if (category === "war") return "war";
  if (category === "battle") return "battle";
  return category === "accident" || category === "natural_disaster" ? "accident" : "event";
}

function organizationWikiCategory(organizationType?: string): WikiCategory {
  if (["order", "merchant_guild", "mercenary_company", "assassin_guild", "knight_order"].includes(organizationType ?? "")) {
    return organizationType as WikiCategory;
  }
  return "organization";
}

function eventRootLabel(category: WikiCategory): string {
  if (category === "war") return "전쟁·전투 › 전쟁";
  if (category === "battle") return "전쟁·전투 › 전투";
  if (category === "accident") return "사건·사고 › 사고";
  return "사건·사고 › 사건";
}

function organizationTypeLabel(organizationType?: string): string {
  switch (organizationType) {
    case "order": return "교단";
    case "merchant_guild": return "상단";
    case "mercenary_company": return "용병단";
    case "assassin_guild": return "암살단";
    case "knight_order": return "기사단";
    default: return "일반 단체";
  }
}
/** 지도 엔티티와 자동 위키 문서를 일치시킨다. 수동 본문은 덮어쓰지 않는다. */
export function syncAutoWikiArticles(project: WorldProject): WorldProject {
  const now = new Date().toISOString();
  const heraldicAssets = [...project.heraldicAssets];
  const assetIds = new Set(heraldicAssets.map((asset) => asset.id));
  const maps = project.maps.map((map) => ({
    ...map,
    factions: map.factions.map((faction, factionIndex) => {
      if (faction.kind !== "country") return faction;
      const flagId = faction.flagAssetId ?? `auto-flag-${faction.id}`;
      const coatId = faction.coatOfArmsAssetId ?? `auto-coat-${faction.id}`;
      const primary = faction.color || ["#315a8a", "#8a4131", "#39704d", "#74518f"][factionIndex % 4];
      if (!assetIds.has(flagId)) {
        heraldicAssets.push({ id: flagId, kind: "flag", name: `${faction.name} 국기`, source: "generated", shape: "rectangle", pattern: factionIndex % 3 === 0 ? "stripes" : factionIndex % 3 === 1 ? "grid" : "solid", symbol: factionIndex % 2 === 0 ? "diamond" : "spade", backgroundColor: primary, patternColor: "#e7d7a6", symbolColor: "#f7f4e8", patternScale: 1, symbolScale: 0.86, symbolOffsetX: 0, symbolOffsetY: 0, createdAt: now, updatedAt: now });
        assetIds.add(flagId);
      }
      if (!assetIds.has(coatId)) {
        heraldicAssets.push({ id: coatId, kind: "coatOfArms", name: `${faction.name} 문장`, source: "generated", shape: factionIndex % 2 === 0 ? "shield" : "circle", pattern: factionIndex % 3 === 1 ? "stripes" : "solid", symbol: factionIndex % 3 === 0 ? "palm" : factionIndex % 3 === 1 ? "diamond" : "spade", backgroundColor: primary, patternColor: "#c9a95f", symbolColor: "#fff7dc", patternScale: 0.9, symbolScale: 0.9, symbolOffsetX: 0, symbolOffsetY: 0, createdAt: now, updatedAt: now });
        assetIds.add(coatId);
      }
      return { ...faction, displayFlag: true, displayCoatOfArms: true, flagAssetId: flagId, coatOfArmsAssetId: coatId };
    }),
  }));
  // 영토는 국가에 종속된 지도 데이터이며 독립 위키 문서를 만들지 않는다.
  const articles = project.wikiArticles.filter((article) => article.sourceEntityType !== "territory");

  for (const map of maps) {
    for (const location of map.locations) {
      const current = getStateAtYear(location.states, map.timeline.currentYear);
      const latest = latestTemporalState(location.states)?.value;
      const state = current ?? latest;
      if (!state) continue;
      const existing = findAutoArticle(articles, map.id, location.id, "location");
      const locationCategory = locationWikiCategory(state.locationType);
      const summary = `${map.title}의 ${state.locationType} · ${state.status} · ${map.timeline.currentYear}년 기준`;
      if (existing) {
        const previousDefaultCategoryId = categoryIdFor(project, existing.category);
        Object.assign(existing, {
          title: existing.manualTitle ? existing.title : state.name,
          category: locationCategory,
          categoryId: existing.categoryId === undefined || existing.categoryId === previousDefaultCategoryId ? categoryIdFor(project, locationCategory) : existing.categoryId,
          summary: existing.manualSummary ? existing.summary : summary,
          tags: Array.from(new Set([...existing.tags, "장소", state.locationType])),
          linkedMapEntityIds: Array.from(new Set([...existing.linkedMapEntityIds, location.id])),
          lastModifiedDate: now,
        });
      } else {
        articles.push(createAutoArticle(project, map.id, location.id, "location", state.name, summary, locationCategory, ["장소", state.locationType]));
      }
    }

    for (const event of map.events) {
      const existing = findAutoArticle(articles, map.id, event.id, "event");
      const categoryLabel = EVENT_CATEGORY_LABELS[event.category];
      const eventCategory = eventWikiCategory(event.category);
      const startLabel = event.startTimeUnknown ? "시작 시점 미정" : `${event.startYear}년`;
      const summary = `${startLabel}${!event.startTimeUnknown && event.endYear !== null && event.endYear !== event.startYear ? `–${event.endYear}년` : ""} · ${eventRootLabel(eventCategory)} › ${categoryLabel}`;
      if (existing) {
        const previousDefaultCategoryId = categoryIdFor(project, existing.category);
        Object.assign(existing, {
          title: existing.manualTitle ? existing.title : event.title,
          category: eventCategory,
          categoryId: existing.categoryId === undefined || existing.categoryId === previousDefaultCategoryId ? categoryIdFor(project, eventCategory) : existing.categoryId,
          eventCategory: event.category,
          eventProfile: event,
          summary: existing.manualSummary ? existing.summary : summary,
          tags: Array.from(new Set([...existing.tags, "사건", categoryLabel])),
          linkedMapEntityIds: Array.from(new Set([...existing.linkedMapEntityIds, event.id])),
          lastModifiedDate: now,
        });
      } else {
        const rootTag = eventCategory === "war" ? "전쟁" : eventCategory === "battle" ? "전투" : eventCategory === "accident" ? "사고" : "사건";
        const article = createAutoArticle(project, map.id, event.id, "event", event.title, summary, eventCategory, [rootTag, categoryLabel]);
        article.eventCategory = event.category;
        article.eventProfile = event;
        articles.push(article);
      }
    }

    for (const faction of map.factions) {
      const existing = findAutoArticle(articles, map.id, faction.id, "faction");
      const category: WikiCategory = faction.kind === "country" ? "country" : faction.kind === "organization" ? organizationWikiCategory(faction.organizationType) : "faction";
      const categoryLabel = faction.kind === "country" ? "국가" : faction.kind === "organization" ? organizationTypeLabel(faction.organizationType) : "세력";
      const summary = faction.leaderName ? `${categoryLabel} 지도자: ${faction.leaderName}` : `${categoryLabel} 지도자 미정`;
      if (existing) {
        const previousDefaultCategoryId = categoryIdFor(project, existing.category);
        const shouldMoveToNewSystemCategory = existing.categoryId === undefined || existing.categoryId === previousDefaultCategoryId;
        Object.assign(existing, {
          title: existing.manualTitle ? existing.title : faction.name,
          category,
          categoryId: shouldMoveToNewSystemCategory ? categoryIdFor(project, category) : existing.categoryId,
          summary: existing.manualSummary ? existing.summary : summary,
          tags: Array.from(new Set([...existing.tags, categoryLabel])),
          linkedMapEntityIds: Array.from(new Set([...existing.linkedMapEntityIds, faction.id])),
          lastModifiedDate: now,
        });
      } else {
        articles.push(createAutoArticle(project, map.id, faction.id, "faction", faction.name, summary, category, [categoryLabel]));
      }
    }

  }

  return {
    ...project,
    maps,
    heraldicAssets,
    wikiArticles: articles,
  };
}
