import {
  EVENT_CATEGORIES,
  EVENT_CATEGORY_LABELS,
  type EventCategory,
  type WikiArticle,
  type WikiCategory,
} from "../model/world";

export function eventCategoriesForSystemKey(
  systemKey?: WikiCategory,
): EventCategory[] {
  if (systemKey === "accident") return ["accident", "natural_disaster"];
  if (systemKey === "war") return ["war"];
  if (systemKey === "battle") return ["battle"];
  return EVENT_CATEGORIES.filter(
    (category) =>
      !["accident", "natural_disaster", "war", "battle"].includes(category),
  );
}

export function eventDocumentGroup(category: EventCategory): string {
  if (category === "war") return "전쟁·전투 › 전쟁";
  if (category === "battle") return "전쟁·전투 › 전투";
  if (["accident", "natural_disaster"].includes(category))
    return "사건·사고 › 사고";
  return "사건·사고 › 사건";
}

export function isEventDocumentCategory(systemKey?: string): boolean {
  return ["event", "accident", "war", "battle"].includes(systemKey ?? "");
}

export function articleKindLabel(article: WikiArticle): string {
  if (isEventDocumentCategory(article.category)) {
    const category = article.eventCategory ?? "incident";
    return `${eventDocumentGroup(category)} › ${EVENT_CATEGORY_LABELS[category]}`;
  }
  if (article.sourceEntityType === "location") return "장소 자동 문서";
  if (article.sourceEntityType === "faction")
    return "국가·세력·단체 자동 문서";
  if (article.sourceEntityType === "territory") return "영토 자동 문서";
  return article.autoGenerated ? "자동 문서" : "수동 문서";
}
